version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running pre-build steps"
  build:
    commands:
      - echo "Running tests"
      - pytest tests/
      - echo "Build complete"
artifacts:
  files:
    - '**/*'
